// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final double INTAKE_SPIN_POWER = 0.3;
    public static final int INTAKE_PORT = 6;
    public static final int DRIVER_CONTROLLER_PORT = 0;
    public static final int GROUND_SWICH_PORT = 3;
    public static final int FOLD_SWICH_PORT = 4;
    public static final double ARM_POWER = 0.1;
    public static final int LIFT_MOTOR_PORT = 5;
    public static final double FF_KG = 0.048; 

    public static class DriveConstants
    {
        public static final int LEFT_TALON = 2;
        public static final int LEFT_VICTOR = 1;
        public static final int RIGHT_TALON = 4;
        public static final int RIGHT_VICTOR = 3;
    }
    /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
}

